# Generated by Django 5.0 on 2024-06-29 00:15

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Churches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.church_image_path)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.ministry_image_path)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.churches')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_member', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Excommunicated'), (1, 'Member'), (2, 'Pastor'), (3, 'Elder'), (4, 'Deacon'), (5, 'Visitor'), (6, 'Discipleship')], default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.person_image_path)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.churches')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ministries')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.positions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ministries',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_ministry_church'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('ministry', 'person'), name='unique_ministry_person'),
        ),
    ]
